### PR TITLE
Development

### PR DESCRIPTION
**Pull request by shoaibkhan17**
-Merging development branch with main

-Analysis of all the three datasets
-Front end application
-Prediction using logistic regression
-Data visualization for heart disease

### CODE REVIEW

**Comment by kamaluddinshakiri** [comment]
Reviewed the code and everything looks perfect based on our group agreement.

**Comment by abdillahinur** [comment]
Reviewed code, build functions as expected. Looks good to merge into master.

**Comment by ghost** [comment]
Reviewed code, functions as expected.

**Comment by TamerIbrahim97** [comment]
Reviewed code, the functions and classes look good. It is good to get merged into master

**Comment by abdelrahmandarwish1** [comment]
Reviewed Code, so feedback regarding the code:
- Try adding some more comments explaining the code
- Use descriptive variable names rather than "df" etc..
- Graphs look good, good job 10/10 graphs

**Comment by abdelrahmandarwish1** [comment]
Reviewed code, graphs looks good 10/10 for graphs

**Pull request merged**
